apiVersion: v1
kind: Service
metadata:
  name: nginx
  labels:
    app: nginx
spec:
  ports:
  - port: 80
    name: web
  clusterIP: None
  selector:
    app: nginx
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: monitor
spec:
  selector:
    matchLabels:
      app: monitor # has to match .spec.template.metadata.labels
  serviceName: "monitor"
  replicas: 1 # by default is 1
  template:
    metadata:
      labels:
        app: monitor # has to match .spec.selector.matchLabels
        policy: egress-all
    spec:
      terminationGracePeriodSeconds: 10
      containers:
      - name: monitor
        image: tidb/installer-centos:7
        imagePullPolicy: "IfNotPresent"
        command: ["/usr/sbin/init"]
        securityContext:
          privileged: true
        ports:
        - containerPort: 80
          name: web
        volumeMounts:
        - name: data1
          mountPath: /data1
  volumeClaimTemplates:
  - metadata:
      name: data1
    spec:
      accessModes: [ "ReadWriteMany" ]
      storageClassName: "standard"
      resources:
        requests:
          storage: 1Gi
