apiVersion: v1
kind: Service
metadata:
  name: monitor
  labels:
    app: monitor
spec:
  ports:
  - port: 9091
    name: pushgateway
  - port: 9090
    name: prometheus
  - port: 3000
    name: grafana
  clusterIP: None
  selector:
    app: monitor
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: monitor
spec:
  selector:
    matchLabels:
      app: monitor # has to match .spec.template.metadata.labels
  serviceName: "monitor"
  replicas: 1 # by default is 1
  template:
    metadata:
      labels:
        app: monitor # has to match .spec.selector.matchLabels
        policy: egress-all
    spec:
      terminationGracePeriodSeconds: 10
      containers:
      - name: monitor
        image: tidb/installer-centos:7
        imagePullPolicy: "IfNotPresent"
        command: ["/usr/sbin/init"]
        securityContext:
          privileged: true
        ports:
        - containerPort: 9091
          name: pushgateway
        - containerPort: 9090
          name: prometheus
        - containerPort: 3000
          name: grafana
        volumeMounts:
        - name: data1
          mountPath: /data1
      volumes:
        - name: cgroup
          hostPath:
            path: /sys/fs/cgroup
            type: Directory

  volumeClaimTemplates:
  - metadata:
      name: data1
    spec:
      accessModes: [ "ReadWriteMany" ]
      storageClassName: "standard"
      resources:
        requests:
          storage: 1Gi
