apiVersion: v1
kind: Service
metadata:
  name: tidb
  labels:
    app: tidb
spec:
  ports:
  - port: 4000
    name: mysql
  - port: 10080
    name: status
  clusterIP: None
  selector:
    app: tidb
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: tidb
spec:
  selector:
    matchLabels:
      app: tidb # has to match .spec.template.metadata.labels
  serviceName: "tidb"
  replicas: 1 # by default is 1
  template:
    metadata:
      labels:
        app: tidb # has to match .spec.selector.matchLabels
    spec:
      terminationGracePeriodSeconds: 10
      containers:
      - name: tidb
        image: tidb/installer-centos:7
        imagePullPolicy: "IfNotPresent"
        command: ["/usr/sbin/init"]
        securityContext:
          privileged: true
        ports:
        - containerPort: 4000
          name: mysql
        - containerPort: 10080
          name: status
        volumeMounts:
        - name: data1
          mountPath: /data1
      volumes:
        - name: cgroup
          hostPath:
            path: /sys/fs/cgroup
            type: Directory
  volumeClaimTemplates:
  - metadata:
      name: data1
    spec:
      accessModes: [ "ReadWriteMany" ]
      storageClassName: "standard"
      resources:
        requests:
          storage: 1Gi
